version: '3.9'

services:
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    container_name: bank_db
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: take
      POSTGRES_PASSWORD: take


    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "finish-registration:1:1,create-documents:1:1,send-documents:1:1,send-ses:1:1,credit-issued:1:1,statement-denied:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      
    depends_on:
      - zookeeper

  calculator:
    build: ./calculator
    container_name: calculator
    ports:
      - "8080:8080"

  deal:
    build: ./deal
    container_name: deal
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bank
      DB_USERNAME: take
      DB_PASSWORD: take
      CALCULATOR_URL: http://calculator:8080/calculator
      KAFKA_URL: kafka:9092
    depends_on:
      - postgres
      - kafka

  statement:
    build: ./statement
    container_name: statement
    ports:
      - "8082:8082"
    environment:
      DEAL_URL: http://deal:8081/deal
  dossier:
    build: ./dossier
    container_name: dossier
    ports:
      - "8083:8083"
    environment:
      KAFKA_URL: kafka:9092
      DEAL_DOCUMENT_URL: http://deal:8081/deal/admin
    depends_on:
      - kafka
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8084:8084"
    environment:
      DEAL_URL: http://deal:8081/deal
      STATEMENT_URL: http://statement:8082/statement

volumes:
  postgres_data: