version: '3.9'

services:
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    container_name: bank_container
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: take
      POSTGRES_PASSWORD: take


    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: